### ISSUE TITLE
Coveralls info under Firefox

### ISSUE THREAD

**Issue by hhfrancois** [codecov/browser-extension#10]
Hi, under firefox it seem that coverall coverage infos is added on the list file. 
When I move mouse, new values is added...
Under chrome, no problem

![capture d ecran 1](https://cloud.githubusercontent.com/assets/5840045/9646948/a9719228-51d8-11e5-964d-228dbfa55368.png)

**Comment by stevepeak** [comment]
This issue will be resolved in an upcoming release. Caused by extension not removing past elements when new pjax requests came through.

**Comment by hhfrancois** [comment]
Great, thx


2015-09-03 20:12 GMT+02:00 Steve Peak <notifications@github.com>:

**Comment by stevepeak** [comment]
Fixes submitted to addon stores. Thank you!
