### ISSUE TITLE
Green color miss

### ISSUE THREAD

**Issue by hhfrancois** [codecov/browser-extension#11]
again under Firefox, toggle button is on, but color not active.
switch button two times (off, on) and that works ...

![capture d ecran 3](https://cloud.githubusercontent.com/assets/5840045/9647036/8435787a-51d9-11e5-8391-51bc8ac3341f.png)
![capture d ecran 4](https://cloud.githubusercontent.com/assets/5840045/9647038/872e9764-51d9-11e5-89c1-ae99243c1aeb.png)

**Comment by stevepeak** [comment]
There are three "modes" for overlaying coverage. Clicking the bottom (or tapping `c` on the keyboard) will toggle between then: `1 -> 2 -> 3 -> 1 etc.`

1. (first by default) Show only "hit & missed"
2. Disable overlay
3. Overlay everything.

You can change this behavior in the [settings of extension](about:addons). Find Codecov and change **Initial coverage view** to your specific choice.

If you have a suggestion to change this behavior please let me know :+1: Thank you!

**Comment by kt3k** [comment]
Hi,

I did the same misunderstanding as @hhfrancois. (Now it's solved.)

I think the UI is a little bit misleading because it seems to suggest there are only 2 modes. (no visual difference of buttons for 1 and 3)

**Comment by stevepeak** [comment]
@kt3k I understand your comment above. I may consider changing this to be 2 modes: On/Off (as the button suggests)

I'll be updating the extension soon and will consider this. Thank you!

**Comment by stevepeak** [comment]
Upcoming version will have only two options: On/Off.
Thanks!

**Comment by kt3k** [comment]
Thanks for updating! I like this simpler version much better! :+1:
