### ISSUE TITLE
Chrome: Stuck on "Coverage loading..."

### ISSUE THREAD

**Issue by vinniefalco** [codecov/browser-extension#16]
Latest chrome on Windows 7:
http://i.imgur.com/QsJJO3U.png

It says "Coverage loading..." and never changes. I can see the corresponding codecov page (at https://codecov.io/github/ximinez)

**Comment by stevepeak** [comment]
Hey @vinniefalco is this issue happening frequently? I visited the page on my setup and it removed the "Coverage loading..." properly.

[Here is a page](https://github.com/ximinez/rippled/blob/832685b64560a9ae2ca817a506be62951f8004d7/src/beast/beast/asio/io_latency_probe.h) that coverage exists and one that does not [here](https://github.com/ximinez/rippled/blob/832685b64560a9ae2ca817a506be62951f8004d7/src/beast/beast/asio/io_latency_probe.h).

This may have been a http timeout... If it repeats I would like to try our debug mode and see what output returns in the web console. To enable go to chrome://extensions/ and click Options on Codecov extension, then check the box that says Debug. This will write via `console.log` data that can help track down issues.

Thanks!

**Comment by vinniefalco** [comment]
After about 20 minutes it started working
