### ISSUE TITLE
Chrome extension: github 'split' files view always shows 100%

### ISSUE THREAD

**Issue by j-funk** [codecov/browser-extension#20]
In the Chrome version of the browser extension, go to any PR which reports incomplete coverage on the diff.  Then head to the 'Files' tab and select 'Split' view.  

You will see that the diff on every file is reporting 100% coverage.

Switch to 'Unified' view.

You will see an accurate report of the coverage for the diff of every file.

**Comment by mahsamor** [comment]
I am seeing the same issue on PRs are as well. Coverage is 100% on diffs on files in 'Split' view and accurate coverage percentage is shown on 'Unified' view.
