### ISSUE TITLE
Not working on Gitlab?

### ISSUE THREAD

**Issue by Sathors** [codecov/browser-extension#24]
I am using Gitlab, and so far I cannot see any differences with the addon installed on Firefox 45.0 on Linux.
For precisions, I installed the version you recommend: [here](https://github.com/codecov/browser-extension/raw/master/dist/firefox.xpi)

Is it a bug, or should I see something?

Thanks.

**Comment by stevepeak** [comment]
Hey @Sathors unfortunately the is not yet compatible with GitLab. We did not have much (any for a while) demand for it so we tabled it for a little. We plan to work on it after our next major release. Thank you!

**Comment by Sathors** [comment]
Okay, sorry for the noise, I was pretty sure I had read somewhere on codecov website that Gitlab was supported by the browser extensions as well, and now I cannot find it anymore.

Thanks for the quick answer!

**Comment by hbetts** [comment]
For some reason I was under the same impression.

Technically there is a little bit of GitLab code in the browser-extension, and the options menu does say _GitLab Endpoint_.

Either way, I'd love to see GitLab support. With the recent, and quite major, improvements in GitLab, I've begun moving all of my GitHub projects over to GitLab. 

So far CodeCov works quite well, leaving the coverage overlay as the only missing feature.

**Comment by stevepeak** [comment]
@hbetts I have not had the time to focus on implementing the extension in GitLab. Would you be interested in helping me out? Could only take an hour or two. I've invited you into our Slack team where you can ping me and we can get this working.
