### ISSUE TITLE
Codecov Chrome extension does not show info on file level in Github

### ISSUE THREAD

**Issue by shayts7** [codecov/browser-extension#26]
Hi,

I do able to see coverage data in folder view:
![image](https://cloud.githubusercontent.com/assets/3765399/14672487/d69dc25c-0700-11e6-8ac9-6dedc9496120.png)

but nothing in file view:
![image](https://cloud.githubusercontent.com/assets/3765399/14672511/fd0cb0f6-0700-11e6-938e-e3ff275a1728.png)

Can someone help with that?

Thanks,
Shay

**Comment by stevepeak** [comment]
@shayts7 we are looking into recent changes to GH that may have affected the extension (not pointing fingers though). Thank you for your patience.

Moving conversation to #27. As it's likely duplicate.
