### ISSUE TITLE
Chrome extension not firing on github page changes, but working if accessed directly?

### ISSUE THREAD

**Issue by Jc2k** [codecov/browser-extension#27]
Possibly a dupe of #26.

If I go here:

https://github.com/codecov/example-python/tree/master/awesome

And see coverage data on the directory view. Then i click on `__init__.py` and i don't see coverage data. So I refresh. Now i see the coverage overlay.

Also if i go direct to:

https://github.com/codecov/example-python/blob/master/awesome/__init__.py

Then I get the coverage overlay.

If i start here:

https://github.com/codecov/example-python/tree/master/

And click into `awesome` i don't get an overlay (and if i refresh i do, and as above going there directly gets me an overlay).

I have tried uninstalling and reinstalling the extension - this is the latest version in the chrome store and Version 49.0.2623.110 (64-bit) of chrome.

**Comment by Jc2k** [comment]
Tried with Version 50.0.2661.75 (64-bit) and still broken.

**Comment by Jc2k** [comment]
I do not have this problem with the firefox version of the extension.

**Comment by stevepeak** [comment]
@Jc2k we are looking into recent changes to GH that may have affected the extension (not pointing fingers though). Thank  you for your patience.

**Comment by stevepeak** [comment]
Fixed and releasing today, thank you!
