### ISSUE TITLE
Enable plugin on Firefox Nightly

### ISSUE THREAD

**Issue by rougeth** [codecov/browser-extension#48]
<img width="554" alt="screen shot 2017-10-14 at 14 05 19" src="https://user-images.githubusercontent.com/431892/31577633-da8ce756-b0e8-11e7-829b-6fa9b641d769.png">

**Comment by justdmitry** [comment]
Looks like duplicate of #44

**Comment by rougeth** [comment]
@justdmitry you're rigth! thanks.
