### ISSUE TITLE
firefox extension not compatiable with quantum

### ISSUE THREAD

**Issue by cyberhck** [codecov/browser-extension#50]
I tried using in firefox quantum, it says it's not compatiable, maybe converting to web extension is a good idea.

Favouring #44

**Comment by sapegin** [comment]
@stevepeak Any chance to look at this? Is it hard to make it compatible with Quantum?

**Comment by cyberhck** [comment]
I think new firefox uses a standard called "Web Extension" once we make it Web Extension, it should work flawlessly. I'd actually give it a try, but I'm not familiar with codecov's codebase.

**Comment by stevepeak** [comment]
I'm sorry to say, but we have reviewed the usage of the browser extension and decided to depreciate it at this point.

The repository will remain available for those who are interested in the codebase.
