### ISSUE TITLE
Overlay shows all hits

### ISSUE THREAD

**Issue by anton-johansson** [codecov/browser-extension#9]
Hey!

Take a look at this file:
https://github.com/Viskan/landing-pages/blob/master/lib/index.js

It shows all hits (green) but it has 0% coverage.

**Comment by stevepeak** [comment]
Hey Anton, I'm not seeing the same as you. What reference sha did you see this on?

- [Codecov report](https://codecov.io/gh/Viskan/landing-pages/lib/index.js?ref=51fdb5c6f3170e0097a5924a12f7f035837e6e95)
- [Overlay in Github](https://github.com/Viskan/landing-pages/blob/51fdb5c6f3170e0097a5924a12f7f035837e6e95/lib/index.js)
